---
abstract: 'Build and install Net-SNMP'
author:
  - 'Eric A. Miller <emiller AT cpan DOT org>'
build_requires:
  Alien::Base: '0.020'
  IO::Socket::SSL: '1.56'
  Net::SSLeay: '1.49'
  Software::License: '0'
  Test::Alien: '0.16'
  Test::More: '0.94'
  perl: '5.010001'
configure_requires:
  Alien::Base::ModuleBuild: '0'
  File::ShareDir: '1.03'
  Module::Build: '0.42'
  PkgConfig: '0.14026'
  Test2::Suite: '0.000067'
  perl: '5.010001'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-SNMP
provides:
  Alien::SNMP:
    file: lib/Alien/SNMP.pm
    version: '3.0509040002'
requires:
  Alien::Base: '0.020'
  File::ShareDir: '1.03'
  parent: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/ollyg/Alien-SNMP/issues
  license: http://opensource.org/licenses/BSD-3-Clause
  repository: http://github.com/ollyg/Alien-SNMP
version: '3.0509040002'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
